import {
    ROOT_CONTAINER_ID,
    createFieldNode,
    createGroupNode,
    cloneTrackerNode,
} from './config.js';

function isContainerNode(node) {
    if (!node) {
        return false;
    }

    return node.kind === 'group' || node.type === 'object' || node.type === 'array';
}

function cloneNodeArray(nodes = []) {
    return nodes.map(cloneTrackerNode);
}

export function flattenSchemaLevel(nodes = []) {
    const result = [];

    for (const node of nodes) {
        if (!node) {
            continue;
        }

        if (node.kind === 'group') {
            result.push(...flattenSchemaLevel(node.children || []));
            continue;
        }

        result.push(node);
    }

    return result;
}

export function buildJsonSchema(fieldTree = []) {
    const root = buildObjectLevel(fieldTree);

    return {
        $schema: 'http://json-schema.org/draft-07/schema#',
        title: 'SceneTracker',
        description: 'Dynamic tracker schema generated by Dynamic Tracker',
        type: 'object',
        properties: root.properties,
        ...(root.required.length ? { required: root.required } : {}),
    };
}

function buildObjectLevel(nodes = []) {
    const properties = {};
    const required = [];

    for (const node of flattenSchemaLevel(nodes)) {
        if (!node?.id) {
            continue;
        }

        properties[node.id] = buildFieldSchema(node);

        if (node.required) {
            required.push(node.id);
        }
    }

    return { properties, required };
}

function buildFieldSchema(node) {
    const description = typeof node.description === 'string' && node.description.trim()
        ? node.description.trim()
        : undefined;

    if (node.type === 'object') {
        const objectLevel = buildObjectLevel(node.children || []);
        return {
            type: 'object',
            ...(description ? { description } : {}),
            properties: objectLevel.properties,
            ...(objectLevel.required.length ? { required: objectLevel.required } : {}),
        };
    }

    if (node.type === 'array') {
        const childFields = flattenSchemaLevel(node.children || []);
        let items;

        if (childFields.length) {
            const objectLevel = buildObjectLevel(node.children || []);
            items = {
                type: 'object',
                properties: objectLevel.properties,
                ...(objectLevel.required.length ? { required: objectLevel.required } : {}),
            };
        } else {
            items = {
                type: 'string',
                ...(description ? { description } : {}),
            };
        }

        return {
            type: 'array',
            ...(description ? { description } : {}),
            items,
        };
    }

    return {
        type: node.type || 'string',
        ...(description ? { description } : {}),
    };
}

export function schemaToPrettyString(fieldTree = []) {
    return JSON.stringify(buildJsonSchema(fieldTree), null, 2);
}

export function findNodeLocation(nodes, uid) {
    return findNodeLocationInternal(nodes, uid, null);
}

function findNodeLocationInternal(nodes, uid, parentNode) {
    for (const node of nodes) {
        if (!node) {
            continue;
        }

        if (node.uid === uid) {
            return {
                node,
                parentNode,
                collection: nodes,
            };
        }

        if (Array.isArray(node.children) && node.children.length) {
            const nested = findNodeLocationInternal(node.children, uid, node);
            if (nested) {
                return nested;
            }
        }
    }

    return null;
}

export function findNodeByUid(nodes, uid) {
    return findNodeLocation(nodes, uid)?.node || null;
}

export function getChildCollection(nodes, parentUid) {
    if (!parentUid || parentUid === ROOT_CONTAINER_ID) {
        return nodes;
    }

    const parent = findNodeByUid(nodes, parentUid);
    if (!parent || !isContainerNode(parent)) {
        return null;
    }

    parent.children = Array.isArray(parent.children) ? parent.children : [];
    return parent.children;
}

export function addNode(nodes, parentUid, node) {
    const collection = getChildCollection(nodes, parentUid);
    if (!collection) {
        return false;
    }

    collection.push(cloneTrackerNode(node));
    return true;
}

export function removeNode(nodes, uid) {
    const location = findNodeLocation(nodes, uid);
    if (!location) {
        return null;
    }

    const index = location.collection.findIndex((entry) => entry.uid === uid);
    if (index === -1) {
        return null;
    }

    const [removed] = location.collection.splice(index, 1);
    return removed || null;
}

export function moveNode(nodes, uid, targetParentUid) {
    const removed = removeNode(nodes, uid);
    if (!removed) {
        return false;
    }

    const success = addNode(nodes, targetParentUid, removed);
    if (!success) {
        addNode(nodes, ROOT_CONTAINER_ID, removed);
        return false;
    }

    return true;
}

export function moveNodeWithinParent(nodes, uid, offset) {
    const location = findNodeLocation(nodes, uid);
    if (!location || !Array.isArray(location.collection)) {
        return false;
    }

    const currentIndex = location.collection.findIndex((entry) => entry?.uid === uid);
    if (currentIndex === -1) {
        return false;
    }

    const targetIndex = currentIndex + Number(offset || 0);
    if (targetIndex < 0 || targetIndex >= location.collection.length || targetIndex === currentIndex) {
        return false;
    }

    const [moved] = location.collection.splice(currentIndex, 1);
    location.collection.splice(targetIndex, 0, moved);
    return true;
}

export function collectContainerOptions(nodes = []) {
    const options = [
        {
            value: ROOT_CONTAINER_ID,
            label: 'Root',
            titleAllowed: false,
        },
    ];

    walkContainerOptions(nodes, {
        path: [],
        titleAllowed: false,
    }, options);

    return options;
}

function walkContainerOptions(nodes, environment, output) {
    for (const node of nodes) {
        if (!node || !isContainerNode(node)) {
            continue;
        }

        const labelName = node.kind === 'group'
            ? (node.name || 'Group')
            : (node.name || node.id || 'Field');

        const labelSuffix = node.kind === 'group'
            ? 'group'
            : node.type;

        const option = {
            value: node.uid,
            label: [...environment.path, `${labelName} [${labelSuffix}]`].join(' › '),
            titleAllowed: environment.titleAllowed || node.type === 'array',
        };

        output.push(option);

        walkContainerOptions(
            Array.isArray(node.children) ? node.children : [],
            {
                path: [...environment.path, `${labelName} [${labelSuffix}]`],
                titleAllowed: option.titleAllowed,
            },
            output,
        );
    }
}

export function validateTrackerData(fieldTree = [], data = {}) {
    const errors = [];
    validateContainer(fieldTree, data, '$', errors);
    return {
        valid: errors.length === 0,
        errors,
    };
}

function validateContainer(nodes, data, path, errors) {
    const flatNodes = flattenSchemaLevel(nodes);

    for (const node of flatNodes) {
        if (!node?.id) {
            continue;
        }

        const value = data?.[node.id];
        const currentPath = `${path}.${node.id}`;

        if (value === undefined || value === null) {
            if (node.required) {
                errors.push(`Missing required field: ${currentPath}`);
            }
            continue;
        }

        if (node.type === 'object') {
            if (!isPlainObject(value)) {
                errors.push(`Expected object at ${currentPath}`);
                continue;
            }
            validateContainer(node.children || [], value, currentPath, errors);
            continue;
        }

        if (node.type === 'array') {
            if (!Array.isArray(value)) {
                errors.push(`Expected array at ${currentPath}`);
                continue;
            }

            const childFields = flattenSchemaLevel(node.children || []);
            if (childFields.length) {
                value.forEach((item, index) => {
                    if (!isPlainObject(item)) {
                        errors.push(`Expected object items at ${currentPath}[${index}]`);
                        return;
                    }
                    validateContainer(node.children || [], item, `${currentPath}[${index}]`, errors);
                });
            }
            continue;
        }

        validatePrimitive(node.type, value, currentPath, errors);
    }
}

function validatePrimitive(type, value, path, errors) {
    switch (type) {
        case 'boolean':
            if (typeof value !== 'boolean') {
                errors.push(`Expected boolean at ${path}`);
            }
            break;
        case 'number':
            if (typeof value !== 'number') {
                errors.push(`Expected number at ${path}`);
            }
            break;
        case 'integer':
            if (!Number.isInteger(value)) {
                errors.push(`Expected integer at ${path}`);
            }
            break;
        case 'string':
        default:
            if (typeof value !== 'string') {
                errors.push(`Expected string at ${path}`);
            }
            break;
    }
}

export function normalizeNodeForSave(rawNode = {}) {
    if (rawNode.kind === 'group') {
        return createGroupNode({
            uid: rawNode.uid,
            name: String(rawNode.name || '').trim(),
            children: cloneNodeArray(rawNode.children || []),
        });
    }

    return createFieldNode({
        uid: rawNode.uid,
        id: String(rawNode.id || '').trim(),
        name: String(rawNode.name || '').trim(),
        type: String(rawNode.type || 'string'),
        description: String(rawNode.description || '').trim(),
        required: !!rawNode.required,
        collapsible: !!rawNode.collapsible,
        title: !!rawNode.title,
        children: cloneNodeArray(rawNode.children || []),
    });
}

export function isPlainObject(value) {
    return !!value && typeof value === 'object' && !Array.isArray(value);
}
